import './arcade.css';
export const API='https://galinhas-arcade-service.juli-ai.chatgpt.site';
type Final={score:number,money:number,seconds:number,outcome:'won'|'lost'};
type Ticket={id:string,token:string};
let generation=0,level=1,gameMode:'solo'|'coop'='solo',latest:Final|null=null,ticket:Promise<Ticket|null>=Promise.resolve(null),registered=false;
let player=crypto.randomUUID();try{const saved=localStorage.getItem('galinhas-player-id');if(saved&&/^[a-f0-9-]{36}$/.test(saved))player=saved as `${string}-${string}-${string}-${string}-${string}`;else localStorage.setItem('galinhas-player-id',player);}catch{}
const node=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id)! as T;
async function request(path:string,body?:unknown){const r=await fetch(API+'/api/'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(12000)});const data=await r.json();if(!r.ok)throw Error(data.error??'No se pudo conectar.');return data;}
function source(){try{return document.referrer?new URL(document.referrer).hostname:'Directo';}catch{return'Directo';}}
function status(text:string){node('record-status').textContent=text;}
export const arcade={
 begin(l:number,m:'solo'|'coop'='solo'){generation++;level=l;gameMode=m;node<HTMLSelectElement>('board-mode').value=m;node<HTMLInputElement>('record-name').maxLength=m==='coop'?20:12;node<HTMLInputElement>('record-name').placeholder=m==='coop'?'JULI + MACA':'JULI';document.querySelector('label[for=record-name]')!.textContent=m==='coop'?'NOMBRE DE PAREJA · 2 A 20 CARACTERES':'TU NOMBRE · 2 A 12 CARACTERES';latest=null;registered=false;node('record-form').classList.add('hidden');node('record-retry').classList.add('hidden');node('records-button').classList.add('hidden');status('');const modal=node<HTMLDialogElement>('arcade-board');if(modal.open)modal.close();ticket=request('runs/start',{level:l,mode:m,player,source:source()}).catch(()=>null);},
 async finish(result:Final){node('records-button').classList.remove('hidden');latest=result;await persist(generation);},
 menu(){node('records-button').classList.remove('hidden');},
};
async function persist(stamp:number){status('Guardando resultado…');node('record-retry').classList.add('hidden');const run=await ticket;if(stamp!==generation)return;if(!run){status('El juego no pudo conectar al iniciar. Esta partida no participa del ranking.');return;}try{const data=await request('runs/finish',{...run,result:latest});if(stamp!==generation)return;status(data.eligible?'¡NUEVO RÉCORD! Dejá tu nombre en el fichín.':'Partida guardada. ¡La próxima superás tu récord!');node('record-form').classList.toggle('hidden',!data.eligible);node('record-submit').removeAttribute('disabled');}catch{if(stamp!==generation)return;status('No se pudo guardar el resultado. Podés reintentar.');node('record-retry').classList.remove('hidden');}}
node('record-retry').onclick=()=>void persist(generation);
node<HTMLFormElement>('record-form').onsubmit=async e=>{e.preventDefault();if(registered)return;const stamp=generation;const run=await ticket;if(!run||stamp!==generation)return;node('record-submit').setAttribute('disabled','');try{const data=await request('runs/register',{...run,name:node<HTMLInputElement>('record-name').value});if(stamp!==generation)return;registered=true;node('record-form').classList.add('hidden');status(`RÉCORD REGISTRADO · ${data.name}`);try{localStorage.setItem('galinhas-last-name',data.name);}catch{}}catch(e){if(stamp===generation){status((e as Error).message);node('record-submit').removeAttribute('disabled');}}};
try{node<HTMLInputElement>('record-name').value=localStorage.getItem('galinhas-last-name')??'';}catch{}
const dialog=node<HTMLDialogElement>('arcade-board');node('records-button').onclick=()=>{dialog.showModal();void load();};node('board-close').onclick=()=>dialog.close();node('board-refresh').onclick=()=>void load();node('board-level').onchange=()=>void load();node('board-sort').onchange=()=>void load();node('board-mode').onchange=()=>void load();
let loadSerial=0;
async function load(){const serial=++loadSerial;node('board-status').textContent='Cargando récords…';node('board-body').replaceChildren();try{const l=node<HTMLSelectElement>('board-level').value,sort=node<HTMLSelectElement>('board-sort').value;const data=await request(`ranking?level=${l}&sort=${sort}&mode=${node<HTMLSelectElement>('board-mode').value}`);if(serial!==loadSerial)return;for(const [i,e] of data.entries.entries()){const tr=document.createElement('tr');for(const text of [String(i+1).padStart(2,'0'),e.name,String(e.score),`R$${e.money}`,`${Math.floor(e.seconds/60)}:${String(Math.floor(e.seconds%60)).padStart(2,'0')}`,String(e.level),e.outcome==='won'?(node<HTMLSelectElement>('board-mode').value==='coop'?'CHEGAMOS!':'CHEGOU!'):'GAME OVER']){const td=document.createElement('td');td.textContent=text;tr.appendChild(td);}if(i<3)tr.classList.add('podium');node('board-body').appendChild(tr);}node('board-status').textContent=data.entries.length?'':'YOUR NAME HERE · Todavía no hay récords. ¿Arrancás vos?';}catch{if(serial===loadSerial)node('board-status').textContent='El ranking no está disponible. Probá actualizar.';}}
